import { CallCenter, Suggestion } from './types/external-crm';

// Demo call centers data for testing bulk import functionality
export const DEMO_CALL_CENTERS: CallCenter[] = [
  {
    id: 'demo-1',
    name: 'Call Center Casablanca',
    country: 'Morocco',
    city: 'Casablanca',
    positions: 25,
    status: 'New',
    phones: ['+212 6XX XXX XXX', '+212 5XX XXX XXX'],
    emails: ['contact@casablanca-callcenter.ma'],
    website: 'https://casablanca-callcenter.ma',
    tags: ['telecom', 'b2b', 'morocco'],
    notes: 'New call center in Casablanca with 25 positions. Interested in telecom services.',
    createdAt: '2024-01-15T10:00:00.000Z',
    updatedAt: '2024-01-15T10:00:00.000Z',
    lastContacted: null,
  },
  {
    id: 'demo-2',
    name: 'Centre d\'Appels Rabat',
    country: 'Morocco',
    city: 'Rabat',
    positions: 40,
    status: 'Cold',
    phones: ['+212 6XX XXX XXX'],
    emails: ['info@rabat-calls.ma'],
    website: 'https://rabat-calls.ma',
    tags: ['telecom', 'outsourcing', 'morocco'],
    notes: 'Established call center in Rabat. Currently using competitor services.',
    createdAt: '2024-01-10T14:30:00.000Z',
    updatedAt: '2024-01-12T09:15:00.000Z',
    lastContacted: '2024-01-12T09:15:00.000Z',
  },
  {
    id: 'demo-3',
    name: 'Call Center Tunis',
    country: 'Tunisia',
    city: 'Tunis',
    positions: 35,
    status: 'Warm',
    phones: ['+216 XX XXX XXX', '+216 XX XXX XXX'],
    emails: ['contact@tunis-callcenter.tn'],
    website: 'https://tunis-callcenter.tn',
    tags: ['telecom', 'multilingual', 'tunisia'],
    notes: 'Growing call center in Tunis. Interested in expanding their telecom infrastructure.',
    createdAt: '2024-01-08T11:20:00.000Z',
    updatedAt: '2024-01-14T16:45:00.000Z',
    lastContacted: '2024-01-14T16:45:00.000Z',
  },
  {
    id: 'demo-4',
    name: 'Centre d\'Appels Dakar',
    country: 'Senegal',
    city: 'Dakar',
    positions: 50,
    status: 'Hot',
    phones: ['+221 XX XXX XXX', '+221 XX XXX XXX', '+221 XX XXX XXX'],
    emails: ['business@dakar-calls.sn'],
    website: 'https://dakar-calls.sn',
    tags: ['telecom', 'b2b', 'senegal', 'large-scale'],
    notes: 'Large call center in Dakar. Currently in negotiation phase for telecom partnership.',
    createdAt: '2024-01-05T13:10:00.000Z',
    updatedAt: '2024-01-16T10:30:00.000Z',
    lastContacted: '2024-01-16T10:30:00.000Z',
  },
  {
    id: 'demo-5',
    name: 'Call Center Abidjan',
    country: 'Ivory Coast',
    city: 'Abidjan',
    positions: 30,
    status: 'Won',
    phones: ['+225 XX XX XX XX'],
    emails: ['contact@abidjan-calls.ci'],
    website: 'https://abidjan-calls.ci',
    tags: ['telecom', 'success', 'ivory-coast'],
    notes: 'Successfully onboarded call center in Abidjan. Now active client.',
    createdAt: '2024-01-03T15:45:00.000Z',
    updatedAt: '2024-01-18T12:00:00.000Z',
    lastContacted: '2024-01-18T12:00:00.000Z',
  },
  {
    id: 'demo-6',
    name: 'Centre d\'Appels Conakry',
    country: 'Guinea',
    city: 'Conakry',
    positions: 20,
    status: 'Lost',
    phones: ['+224 XXX XX XX XX'],
    emails: ['info@conakry-calls.gn'],
    website: 'https://conakry-calls.gn',
    tags: ['telecom', 'lost', 'guinea'],
    notes: 'Call center in Conakry that chose a competitor. Keep for future reference.',
    createdAt: '2024-01-01T09:30:00.000Z',
    updatedAt: '2024-01-17T14:20:00.000Z',
    lastContacted: '2024-01-17T14:20:00.000Z',
  },
  {
    id: 'demo-7',
    name: 'Call Center Yaoundé',
    country: 'Cameroon',
    city: 'Yaoundé',
    positions: 45,
    status: 'New',
    phones: ['+237 XXX XXX XXX', '+237 XXX XXX XXX'],
    emails: ['contact@yaounde-callcenter.cm'],
    website: 'https://yaounde-callcenter.cm',
    tags: ['telecom', 'b2b', 'cameroon', 'growing'],
    notes: 'New call center in Yaoundé. Showing strong interest in telecom solutions.',
    createdAt: '2024-01-16T08:15:00.000Z',
    updatedAt: '2024-01-16T08:15:00.000Z',
    lastContacted: null,
  },
  {
    id: 'demo-8',
    name: 'Centre d\'Appels Marrakech',
    country: 'Morocco',
    city: 'Marrakech',
    positions: 28,
    status: 'Cold',
    phones: ['+212 6XX XXX XXX'],
    emails: ['business@marrakech-calls.ma'],
    website: 'https://marrakech-calls.ma',
    tags: ['telecom', 'tourism', 'morocco'],
    notes: 'Call center in Marrakech serving tourism industry. Initial contact made.',
    createdAt: '2024-01-12T16:00:00.000Z',
    updatedAt: '2024-01-13T11:30:00.000Z',
    lastContacted: '2024-01-13T11:30:00.000Z',
  },
  {
    id: 'demo-9',
    name: 'Call Center Sfax',
    country: 'Tunisia',
    city: 'Sfax',
    positions: 32,
    status: 'Warm',
    phones: ['+216 XX XXX XXX', '+216 XX XXX XXX'],
    emails: ['contact@sfax-callcenter.tn'],
    website: 'https://sfax-callcenter.tn',
    tags: ['telecom', 'industrial', 'tunisia'],
    notes: 'Industrial call center in Sfax. Currently evaluating telecom providers.',
    createdAt: '2024-01-09T12:45:00.000Z',
    updatedAt: '2024-01-15T13:20:00.000Z',
    lastContacted: '2024-01-15T13:20:00.000Z',
  },
  {
    id: 'demo-10',
    name: 'Centre d\'Appels Saint-Louis',
    country: 'Senegal',
    city: 'Saint-Louis',
    positions: 22,
    status: 'Hot',
    phones: ['+221 XX XXX XXX'],
    emails: ['info@saintlouis-calls.sn'],
    website: 'https://saintlouis-calls.sn',
    tags: ['telecom', 'regional', 'senegal'],
    notes: 'Regional call center in Saint-Louis. Very interested in partnership.',
    createdAt: '2024-01-07T10:30:00.000Z',
    updatedAt: '2024-01-17T15:45:00.000Z',
    lastContacted: '2024-01-17T15:45:00.000Z',
  }
];

// Demo suggestions data for testing import functionality
export const DEMO_SUGGESTIONS: Suggestion[] = [
  {
    id: 'sugg-1',
    name: 'Call Center Fès',
    address: '123 Boulevard Hassan II, Fès, Morocco',
    phones: ['+212 6XX XXX XXX', '+212 5XX XXX XXX'],
    country: 'Morocco',
    city: 'Fès',
    positions: 38,
    source: 'google',
    exported: false,
    createdAt: '2024-01-18T09:00:00.000Z',
    website: 'https://fes-callcenter.ma',
    email: 'contact@fes-callcenter.ma',
  },
  {
    id: 'sugg-2',
    name: 'Centre d\'Appels Sousse',
    address: '456 Avenue Habib Bourguiba, Sousse, Tunisia',
    phones: ['+216 XX XXX XXX'],
    country: 'Tunisia',
    city: 'Sousse',
    positions: 26,
    source: 'facebook',
    exported: false,
    createdAt: '2024-01-18T10:15:00.000Z',
    website: 'https://sousse-calls.tn',
    email: 'info@sousse-calls.tn',
  },
  {
    id: 'sugg-3',
    name: 'Call Center Thiès',
    address: '789 Rue de l\'Indépendance, Thiès, Senegal',
    phones: ['+221 XX XXX XXX', '+221 XX XXX XXX'],
    country: 'Senegal',
    city: 'Thiès',
    positions: 42,
    source: 'google',
    exported: false,
    createdAt: '2024-01-18T11:30:00.000Z',
    website: 'https://thies-callcenter.sn',
    email: 'business@thies-callcenter.sn',
  },
  {
    id: 'sugg-4',
    name: 'Centre d\'Appels Bouaké',
    address: '321 Boulevard de la République, Bouaké, Ivory Coast',
    phones: ['+225 XX XX XX XX'],
    country: 'Ivory Coast',
    city: 'Bouaké',
    positions: 29,
    source: 'csv',
    exported: false,
    createdAt: '2024-01-18T12:45:00.000Z',
    website: 'https://bouake-calls.ci',
    email: 'contact@bouake-calls.ci',
  },
  {
    id: 'sugg-5',
    name: 'Call Center Kankan',
    address: '654 Avenue de l\'Indépendance, Kankan, Guinea',
    phones: ['+224 XXX XX XX XX'],
    country: 'Guinea',
    city: 'Kankan',
    positions: 18,
    source: 'google',
    exported: false,
    createdAt: '2024-01-18T14:00:00.000Z',
    website: 'https://kankan-callcenter.gn',
    email: 'info@kankan-callcenter.gn',
  },
  {
    id: 'sugg-6',
    name: 'Centre d\'Appels Douala',
    address: '987 Boulevard de la Liberté, Douala, Cameroon',
    phones: ['+237 XXX XXX XXX', '+237 XXX XXX XXX'],
    country: 'Cameroon',
    city: 'Douala',
    positions: 55,
    source: 'facebook',
    exported: false,
    createdAt: '2024-01-18T15:15:00.000Z',
    website: 'https://douala-calls.cm',
    email: 'business@douala-calls.cm',
  },
  {
    id: 'sugg-7',
    name: 'Call Center Agadir',
    address: '147 Boulevard du 20 Août, Agadir, Morocco',
    phones: ['+212 6XX XXX XXX'],
    country: 'Morocco',
    city: 'Agadir',
    positions: 31,
    source: 'google',
    exported: false,
    createdAt: '2024-01-18T16:30:00.000Z',
    website: 'https://agadir-callcenter.ma',
    email: 'contact@agadir-callcenter.ma',
  },
  {
    id: 'sugg-8',
    name: 'Centre d\'Appels Bizerte',
    address: '258 Avenue de la République, Bizerte, Tunisia',
    phones: ['+216 XX XXX XXX'],
    country: 'Tunisia',
    city: 'Bizerte',
    positions: 24,
    source: 'csv',
    exported: false,
    createdAt: '2024-01-18T17:45:00.000Z',
    website: 'https://bizerte-calls.tn',
    email: 'info@bizerte-calls.tn',
  }
];

// Function to populate demo data
export const populateDemoData = async () => {
  // This would be used to populate the database with demo data
  // Implementation would depend on the specific requirements
  console.log('Demo data ready for import:', {
    callCenters: DEMO_CALL_CENTERS.length,
    suggestions: DEMO_SUGGESTIONS.length
  });
};