// GET /api/external-crm/today - Get today's tasks and calendar events combined
import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase-admin';
import { TaskService } from '@/lib/services/task-service';
import { GroupsPostingGeneratorService } from '@/lib/services/groups-posting-generator-service';

interface CalendarEvent {
  id: string;
  title: string;
  description?: string;
  date: string;
  time?: string;
  location?: string;
  type: 'meeting' | 'call' | 'task' | 'reminder';
  color?: string;
  callCenterId?: string;
  callCenterName?: string;
  relatedType?: 'step' | 'callLog';
  relatedId?: string;
  status?: 'completed' | 'pending';
  completedAt?: string | null;
  createdAt: string;
  updatedAt: string;
  firebaseTaskId?: string;
  summary?: string;
}

interface FirebaseTask {
  id: string;
  date: Date;
  assignedTo: string;
  groupId?: string;
  accountId?: string;
  templateId?: string;
  notes?: string;
  status?: 'pending' | 'completed';
  createdAt?: Date;
  doneAt?: Date;
}

interface TodayItem {
  id: string;
  title: string;
  description?: string;
  date: string;
  time?: string;
  completed: boolean;
  completedAt?: string;
  source: 'firebase' | 'calendar' | 'groups';
  type?: 'meeting' | 'call' | 'task' | 'reminder';
  location?: string;
  callCenterId?: string;
  callCenterName?: string;
  groupId?: string;
  accountId?: string;
  summary?: string;
}

// GET /api/external-crm/today - Get today's tasks and calendar events combined
export async function GET() {
  try {
    // Get user's local timezone (default to Casablanca if not available)
    const userTimezone = 'Africa/Casablanca';
    const now = new Date();
    
    // Create dates based on user's timezone
    const today = new Date(now.toLocaleString('en-US', { timeZone: userTimezone }));
    const todayStr = today.toISOString().split('T')[0]; // YYYY-MM-DD format in user's timezone
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    const tomorrowStr = tomorrow.toISOString().split('T')[0];
    
    // For Firebase tasks, use UTC boundaries but calculate based on local timezone
    const startOfDay = new Date(today);
    const endOfDay = new Date(tomorrow);

    console.log('📅 Getting today\'s combined tasks and calendar events for:', {
      userTimezone,
      todayStr,
      tomorrowStr,
      localNow: now.toLocaleString('en-US', { timeZone: userTimezone }),
      utcNow: now.toISOString()
    });

    // Get calendar events for today (using user's local date)
    const calendarSnapshot = await adminDb.collection('calendarEvents').get();
    const calendarEvents: CalendarEvent[] = [];
    calendarSnapshot.forEach((doc) => {
      const data = doc.data();
      calendarEvents.push({
        id: doc.id,
        title: data.title || '',
        description: data.description || '',
        date: data.date || '',
        time: data.time || '',
        location: data.location || '',
        type: data.type || 'meeting',
        color: data.color || '',
        callCenterId: data.callCenterId || '',
        callCenterName: data.callCenterName || '',
        relatedType: data.relatedType || '',
        relatedId: data.relatedId || '',
        status: data.status || 'pending',
        completedAt: data.completedAt || null,
        createdAt: data.createdAt || '',
        updatedAt: data.updatedAt || '',
        firebaseTaskId: data.firebaseTaskId || '',
        summary: data.summary || '',
      } as CalendarEvent);
    });

    // Filter calendar events for today
    const todayCalendarEvents = calendarEvents.filter(event =>
      event.date >= todayStr && event.date < tomorrowStr
    );

    // Get Firebase tasks for today
    const allTasks = await TaskService.getAllTasks();
    const todayTasks = allTasks
      .filter(task => {
        const taskDate = task.date;
        const isToday = taskDate >= startOfDay && taskDate < endOfDay;

        // Check if this is an auto-generated posting task by examining notes
        let isAutoGeneratedPostingTask = false;
        if (task.notes) {
          try {
            // Try to parse notes as JSON first
            const parsedNotes = JSON.parse(task.notes);
            if (parsedNotes && typeof parsedNotes === 'object') {
              // Check if title indicates auto-generated task
              isAutoGeneratedPostingTask = parsedNotes.title?.includes('Auto-generated schedule') ||
                                          parsedNotes.description?.includes('Auto-generated schedule');
            } else {
              // Check raw notes string
              isAutoGeneratedPostingTask = task.notes.includes('Auto-generated schedule');
            }
          } catch (error) {
            // If JSON parsing fails, check raw notes string
            isAutoGeneratedPostingTask = task.notes.includes('Auto-generated schedule');
          }
        }

        // Also check if this is a test task
        if (!isAutoGeneratedPostingTask && task.notes) {
          try {
            const parsedNotes = JSON.parse(task.notes);
            if (parsedNotes && typeof parsedNotes === 'object') {
              isAutoGeneratedPostingTask = parsedNotes.title?.includes('🧪 TEST:') ||
                                          parsedNotes.description?.includes('🧪 TEST:');
            } else {
              isAutoGeneratedPostingTask = task.notes.includes('🧪 TEST:');
            }
          } catch (error) {
            isAutoGeneratedPostingTask = task.notes.includes('🧪 TEST:');
          }
        }

        // Only show manual tasks in "Today's Tasks" section
        return isToday && !isAutoGeneratedPostingTask;
      })
      .map(task => {
        let title = 'Task';
        let description = '';

        try {
          // Try to parse notes as JSON (new format)
          if (task.notes) {
            const parsedNotes = JSON.parse(task.notes);
            if (parsedNotes && typeof parsedNotes === 'object') {
              title = parsedNotes.title || parsedNotes.description || 'Task';
              description = parsedNotes.description || '';
            } else {
              // Fallback for old format (just string)
              title = task.notes;
              description = task.notes;
            }
          }
        } catch (error) {
          // Fallback if JSON parsing fails
          title = task.notes || 'Task';
          description = task.notes || '';
        }

        return {
          id: task.id!,
          title,
          description,
          date: task.date.toISOString().split('T')[0],
          time: task.date.toTimeString().split(' ')[0],
          completed: task.status === 'completed',
          completedAt: task.doneAt?.toISOString(),
          source: 'firebase' as const,
          groupId: task.groupId,
          accountId: task.accountId,
        };
      });

    // Get today's group posting tasks
    const todaysGroupTasks = await GroupsPostingGeneratorService.getTodaysTasks();
    console.log('📊 Today\'s group posting tasks:', todaysGroupTasks.length);

    // Convert calendar events to unified format, but exclude those linked to Firebase tasks to avoid duplication
    const convertedCalendarEvents: TodayItem[] = todayCalendarEvents
      .filter((event: CalendarEvent) => !event.firebaseTaskId) // Exclude calendar events that are linked to Firebase tasks
      .map((event: CalendarEvent) => ({
        id: `calendar-${event.id}`,
        title: event.title,
        description: event.description || '',
        date: event.date,
        time: event.time,
        completed: event.status === 'completed',
        completedAt: event.completedAt || undefined,
        source: 'calendar' as const,
        type: event.type,
        location: event.location,
        callCenterId: event.callCenterId,
        callCenterName: event.callCenterName,
        summary: event.summary || '',
      }));

    // Convert Firebase tasks to unified format
    const convertedFirebaseTasks: TodayItem[] = todayTasks.map((task: any) => ({
      id: task.id,
      title: task.title,
      description: task.description,
      date: task.date,
      time: task.time,
      completed: task.completed,
      completedAt: task.completedAt,
      source: 'firebase' as const,
      groupId: task.groupId,
      accountId: task.accountId,
    }));

    // Convert group posting tasks to unified format
    const convertedGroupTasks: TodayItem[] = todaysGroupTasks.map((task: any) => ({
      id: `group-${task.id}`,
      title: `Post to ${task.groupName}`,
      description: `Post "${task.textTitle}" to ${task.groupName} using ${task.accountName}`,
      date: task.scheduledTime.split('T')[0],
      time: task.scheduledTime.split('T')[1]?.split('.')[0] || '',
      completed: task.status === 'completed',
      completedAt: task.status === 'completed' ? task.updatedAt : undefined,
      source: 'groups' as const,
      groupId: task.groupId,
      accountId: task.accountId,
      summary: `Group: ${task.groupName} (${task.groupMemberCount} members)`,
    }));

    // Combine and sort by time
    const allItems = [...convertedFirebaseTasks, ...convertedCalendarEvents, ...convertedGroupTasks]
      .sort((a, b) => {
        const timeA = a.time || '23:59';
        const timeB = b.time || '23:59';
        return timeA.localeCompare(timeB);
      });

    const response = {
      date: todayStr,
      totalItems: allItems.length,
      completedItems: allItems.filter(item => item.completed).length,
      pendingItems: allItems.filter(item => !item.completed).length,
      firebaseTasks: convertedFirebaseTasks.length,
      calendarEvents: convertedCalendarEvents.length,
      groupTasks: convertedGroupTasks.length,
      items: allItems
    };

    console.log('✅ Today\'s combined data:', {
      total: allItems.length,
      firebase: convertedFirebaseTasks.length,
      calendar: convertedCalendarEvents.length,
      groups: convertedGroupTasks.length,
      completed: response.completedItems
    });

    return NextResponse.json(response);
  } catch (error) {
    console.error('❌ Error fetching today\'s combined data:', error);
    return NextResponse.json(
      { error: 'Failed to fetch today\'s tasks and calendar events' },
      { status: 500 }
    );
  }
}